name: Build Unit Tests Report

on:
  workflow_run:
    workflows:
      - Build with unit tests
    types:
      - completed

permissions:
  actions: read
  statuses: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}

    steps:
      - uses: marocchino/action-workflow_run-status@54b6e87d6cb552fc5f36dbe9a722a6048725917a

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts/

      - name: Surefire Report
        uses: mikepenz/action-junit-report@16a9560bd02f11e7e3bf6b3e2ef6bba6c9d07c32
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          detailed_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.event.workflow_run.head_sha }}
          check_name: Build Test Report
