name: Build with unit tests

on:
  push:
    branches: [ develop, release/** ]
  pull_request:
    branches: [ develop, release/** ]
    types: [opened, synchronize, reopened, labeled]

jobs:
  build:
    runs-on: k8s-runner-build

    if: >
      github.event_name == 'push'
      || (contains(github.event.pull_request.labels.*.name, 'build')
         && (github.event.action != 'labeled' || github.event.label.name == 'build'))

    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ github.workflow }}

      - name: Build with Maven
        run: mvn clean test -fae -T 2 -B -V -DcloudBuild -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports-${{ github.run_id }}
          path: |
            **/target/rat.txt
            **/target/surefire-reports/*
